export const SHOWMODALOVERLAY = 'SHOWMODALOVERLAY';
export const  AFTERLROUTELOADING = "AFTERLROUTELOADING";
export const  CALCULATEPOLICYFEE = "CALCULATEPOLICYFEE";
export const TASK_EXPERIENCE = "TASK_EXPERIENCE";
export const QUERY_DRIVEFIRSTINFO = "QUERY_DRIVEFIRSTINFO";
export const GET_CARDNOANDPHONE = "GET_CARDNOANDPHONE";
export const ORDER_INSURE_CODE = "ORDER_INSURE_CODE";
export const GET_ORDERLIST = "GET_ORDERLIST";
export const GET_CARDNOANDPHONES = "GET_CARDNOANDPHONES";
//加入好司机
export const GETFIRIFO = "GETFIRIFO";
export const TOJOIN = "TOJOIN";
export const GETZJB = "GETZJB";
export const GETID = "GETID";
export const GETREACH = "GETREACH";
export const GETVERSION = "GETVERSION";
export const GEENCRYPTID = "GEENCRYPTID";

//新用户活动
export const GETUSERSCORE = "GETUSERSCORE";


//vuex
export const CHANGEWORD = "CHANGEWORD";